export const reportDocumentStyles = `
@page{size:A4;margin:16mm 14mm}
*{box-sizing:border-box}html{background:#fff}body{margin:0;color:#213e35;background:#fff;font:11px/1.65 Arial,'Microsoft YaHei','Noto Sans CJK SC',sans-serif;-webkit-print-color-adjust:exact;print-color-adjust:exact}
h1,h2,h3,p{margin:0}p{margin:8px 0}h1,h2,h3{break-after:avoid}h1{font-size:38px;line-height:1.12;font-weight:400}h2{font-size:23px;line-height:1.2;font-weight:400}h3{font-size:14px;margin:15px 0 6px;font-weight:600}a{color:#39614f}small{font-size:9px;color:#607569}
.cover{height:262mm;padding:10mm;display:flex;flex-direction:column;position:relative;color:#f1ede1;background:#0d211d;border:1px solid #bca36a;outline:1px solid #486256;outline-offset:-4mm;break-after:page;overflow:hidden}
.tag{font-size:9px;letter-spacing:2px;color:#d4ba80}.cover-top{display:flex;justify-content:space-between;align-items:center;gap:20px}.cover-brand{font-size:16px;letter-spacing:4px}.cover h1{margin-top:10mm;font-size:39px;max-width:145mm}.cover-subtitle{font-size:12px;color:#b9cec2;margin:5mm 0 0;letter-spacing:1px}
.cover .cover-art{display:block;width:100%;height:105mm;object-fit:contain;flex-shrink:0;margin:5mm 0}.cover-name{font-size:27px;font-weight:400;line-height:1.2;overflow-wrap:anywhere}.cover .birth-meta{color:#c1d2c8;font-size:11px}.identity{display:flex;align-items:center;gap:16px;margin-top:auto;padding-top:5mm;border-top:1px solid #526755}.identity img{width:58px;height:58px;object-fit:contain}.identity h3{color:#eee2c4;font-size:17px;font-weight:400;margin:0}.identity p{font-size:10px;color:#c1d2c8;margin:3px 0}.cover-date{margin-top:5mm;font-size:9px;letter-spacing:1px;color:#c7b787}
.report-section{margin:0 0 18px;break-before:page}.section-heading{display:flex;align-items:center;gap:18px;background:#102a23;color:#f4eee0;min-height:39mm;padding:20px 22px;border-top:2px solid #bda46f;margin:0 0 22px;break-inside:avoid;break-after:avoid}.section-heading .section-number{display:block;font-size:11px;color:#d3b980;letter-spacing:2px;margin-bottom:10px}.section-heading .section-copy{flex:1}.section-heading h2{color:#f4eee0;font-size:23px;margin:0;line-height:1.22;border:0;padding:0}.section-art{width:145px;height:108px;object-fit:contain;flex-shrink:0}.section-heading .report-ornament{width:80px;height:80px;color:#c2a86c;margin:0}
.roadmap{break-after:page;padding:7mm 0 0}.roadmap-head{display:flex;align-items:center;gap:25px;border-bottom:1px solid #c7bea5;padding-bottom:22px;margin-bottom:22px}.roadmap-head h2{font-size:32px}.roadmap-head .report-ornament{width:70px;height:70px;margin:0}.roadmap .tag{color:#8e7544}.roadmap p{color:#597065}.contents{list-style:none;padding:0;margin:20px 0}.contents li{border-bottom:1px solid #dce3d9}.contents a{display:flex;align-items:center;gap:18px;padding:10px 5px;text-decoration:none;font-size:12px}.contents b{color:#a1874e;font-size:11px;font-weight:400}.contents span{margin-left:auto;color:#9c854f}.reading-key{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:24px}.reading-key>div{background:#f2f4ec;border-top:2px solid #bda46f;padding:14px}.reading-key strong{font-size:12px}.reading-key p{font-size:10px;line-height:1.5}
.pillars{display:flex;border:1px solid #c6d3c6;margin:18px 0;break-inside:avoid;background:#f6f6ee}.pillar{flex:1;text-align:center;border-top:4px solid var(--element);padding:13px 7px}.pillar+.pillar{border-left:1px solid #d4ddcf}.pillar strong{display:block;font-size:35px;font-weight:400;line-height:1.4}.pillar p{font-size:10px;margin:5px 0}.pillar>small{display:block;letter-spacing:1px;margin-bottom:6px}.pillar>div{font-size:11px;color:#64705f}
.note{font-size:10px;line-height:1.6;padding:11px 14px;background:#f2f4eb;color:#526b5d;border-left:2px solid #bda46f;margin:10px 0}.report-section article{padding:1px 16px 10px;border-left:2px solid #c2ccb9;margin-bottom:16px;break-inside:avoid}.report-section article h3{color:#294f40;font-weight:600}.report-section article p:last-child{margin-bottom:0}.analysis-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px 18px}.analysis-grid article{margin:0;padding:0 10px 8px}.analysis-grid h3{font-size:12px;margin-top:6px}.analysis-grid p{font-size:10px;line-height:1.6}
table{width:100%;border-collapse:collapse;table-layout:auto;font-size:10px;line-height:1.55;margin:16px 0}th{background:#1b3c31;color:#f0e5cc;text-align:left;font-weight:400;font-size:9px;letter-spacing:.3px}td,th{padding:9px 8px;vertical-align:top;overflow-wrap:anywhere;border-bottom:1px solid #d8dfd2}tbody tr:nth-child(even){background:#f5f6ef}thead{display:table-header-group}tr{break-inside:avoid}td:first-child{color:#375840}td:last-child{color:#536b5e}
.qimen-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;border:1px solid #bba575;padding:8px;background:#eaf0e5;margin:18px 0;break-inside:avoid}.qimen-grid>div{background:#fffef8;border:1px solid #becbb9;border-top:3px solid #728e79;min-height:35mm;padding:12px}.qimen-grid>div:nth-child(5){background:#dfe9d8}.qimen-grid strong{display:block;font-size:27px;font-weight:400}.qimen-grid p{font-size:10px;margin:4px 0}
.consultant-comment{white-space:pre-wrap;overflow-wrap:anywhere}.consultation-card{display:flex;align-items:center;gap:24px;padding:24px;margin-top:24px;background:#112c23;color:#eae9dc;border:1px solid #ac925d;break-inside:avoid}.consultation-card img{width:110px;height:110px;object-fit:contain}.consultation-card h3{font-size:22px;font-weight:400;margin-top:0;color:#f0e0bb}.consultation-card .expert-role{color:#c7b98e}.consultation-card p{font-size:10px;color:#c6d3c7}.consultation-card a{display:inline-block;color:#e7d1a2;border-bottom:1px solid #8e815c;margin-right:20px;text-decoration:none;padding:4px 0}
footer{margin-top:25px;padding-top:12px;border-top:1px solid #ccd4c4;color:#70816e;font-size:9px}.report-section p{orphans:3;widows:3}
.conclusion-section article{padding:0 12px 6px;margin-bottom:9px}.conclusion-section article h3{font-size:12px;margin-top:9px}.conclusion-section article p{font-size:10px;line-height:1.5;margin:5px 0}.reading-body article{padding-bottom:8px;margin-bottom:12px}.reading-body .question{color:#61725a;font-size:10px;margin-top:5px}.reading-body .evidence{margin-top:4px;line-height:1.35}.reading-body h3{margin-top:9px}.reading-body p{margin:6px 0}
@media screen{html{background:#e6e9e2}body{max-width:800px;padding:30px;margin:20px auto;box-shadow:0 8px 40px #182c1e22}.report-section{margin-top:45px}.cover{height:990px}.roadmap{padding-top:45px}}
`;
